### ISSUE TITLE
How to analyze a site as an authenticated user?

### ISSUE THREAD

**Issue by michael1026** [SoheilKhodayari/TheThing#4]
Hello,

First off, amazing project. Thank you a ton for making this available.

I'm trying to analyze a website that redirects if you're not authenticated. What are my options here? I've looked through all of the documentation, but did not see an option.

Side question: Is there any documentation on interpreting the results? They're not quite clear at first glance.

Thanks!

**Comment by SoheilKhodayari** [comment]
Hi, 

Thanks so much for your interest in JAW and for creating this issue! 

For authentication, the crawling script should be minimally modified to login to the specific website under test. This can be implemented [here](https://github.com/SoheilKhodayari/JAW/blob/3201d25067ffdd93f580df5db68e4eff804b0255/crawler/crawler.js#L239)  for the Chrome-based crawler or [here](https://github.com/SoheilKhodayari/JAW/blob/master/crawler/crawler-taint.js#L463) for [Foxhound](https://github.com/SAP/project-foxhound) (Firefox-based with in-browser dynamic taint tracking). For example:

```js
var loginUrl = "https://example.com/login";
await page.goto(loginUrl, {waitUntil: 'networkidle0'});

await page.evaluate( () => {

	var usernameInput = document.getElementById("username");
        usernameInput.setAttribute("value",  "test@gmail.com");
	
	var passwordInput = document.getElementById("password");
        passwordInput.setAttribute("value",  "test@gmail.com");
      
        document.getElementById("login-submit").click();
});

```

PS: JAW-v1 had a Selenium-based crawler adopting a similar approach (see, i.e., [here](https://github.com/SoheilKhodayari/JAW/blob/3201d25067ffdd93f580df5db68e4eff804b0255/crawler/hpg_crawler/sites/template/scripts/Auth.py)). However, this did not made it to the puppeteer-based and playwright-based crawlers. 


For interpreting the outputs, there is some minimal documentation [here](https://github.com/SoheilKhodayari/JAW/?tab=readme-ov-file#how-to-interpret-the-output-of-the-analysis). 

Assuming testing a domain like `example.com`, the crawler will create a folder named `example.com`, which contains one folder for each webpage found (named with SHA256 hash of the URL).

Inside each webpage folder, you can normally find the following outputs:

- `sinks.out.json`: list of sinks found
- `sources.out.json`: list of sources found if applicable (e.g., potentially clobberable variables)
- `sinks.flows.out`: list of data flows found via static analysis (backward program slicing from sinks to sources)
- `taintflows.json`: list of dynamic data flows found (when using foxhound). 
- `url.out`: url of the current webpage
- `index.html`: snapshot of the webpage
- the list of the javascript files, named with integers 1 to N based on their parsing order (also beautified versions with [sourcemaps](https://github.com/SoheilKhodayari/JAW/blob/master/crawler/crawler-taint.js#L303)) 
- `cookies.json`: snapshot of the cookies
- `webstorage.json`: snapshot of the Web storage values
- `requests.json`: requests intercepted dynamically (e.g., XMLHttpRequests)
- `nodes.csv` / `rels.csv` : node and edges for the code property graphs.   


Also, as a side note, it may be better to use the updated version in the [main repository](https://github.com/SoheilKhodayari/JAW/), which is more stable. 

Hope it helps!

**Comment by michael1026** [comment]
Thank you!
